# Generated by Django 5.0 on 2023-12-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
